<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0-windows10.0.18362.0</TargetFramework>
		<UseWPF>true</UseWPF>
		<ApplicationIcon>Assets/Icons/AuraEcho.ico</ApplicationIcon>
		<RuntimeIdentifier>win-x64</RuntimeIdentifier>
		<SatelliteResourceLanguages>zh-Hans;en-us</SatelliteResourceLanguages>
		<Nullable>enable</Nullable>
		<AssemblyTitle>灵光回声</AssemblyTitle>
		<Product>灵光回声</Product>
		<ApplicationManifest>app.manifest</ApplicationManifest>
	</PropertyGroup>
	<ItemGroup>
		<ApplicationDefinition Remove="App.xaml" />
		<None Remove="Assets\Icons\AuraEcho.ico" />
		<None Remove="Assets\Images\pay_banner.png" />
		<None Remove="Assets\Images\pay_banner_shapes.png" />
		<None Remove="Assets\PDF\SubscriptionTerms.pdf" />
		<Content Include="Assets\PDF\EULA.pdf">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Content Include="Assets\PDF\SubscriptionTerms.pdf">
		  <CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</Content>
		<Page Include="App.xaml" />
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="Hardcodet.NotifyIcon.Wpf" Version="2.0.1" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.8" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="9.0.8" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.8">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="10.0.8" />
		<PackageReference Include="Microsoft.Toolkit.Uwp.Notifications" Version="7.0.0" />
		<PackageReference Include="Microsoft.Web.WebView2" Version="1.0.3967.48" />
		<PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.135" />
		<PackageReference Include="Prism.DryIoc" Version="8.1.97" />
		<PackageReference Include="QRCoder" Version="1.8.0" />
		<PackageReference Include="Rougamo.Fody" Version="5.0.0" />
		<PackageReference Include="TaskScheduler" Version="2.12.2" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\..\Shared\AuraEcho.PluginContracts\AuraEcho.PluginContracts.csproj" />
		<ProjectReference Include="..\..\Shared\AuraEcho.Design\AuraEcho.Design.csproj" />
		<ProjectReference Include="..\..\Shared\AuraEcho.Core\AuraEcho.Core.csproj" />
		<ProjectReference Include="..\..\Shared\AuraEcho.UIToolkit\AuraEcho.UIToolkit.csproj" />
	</ItemGroup>
	<ItemGroup>
	  <Resource Include="Assets\Icons\AuraEcho.ico" />
	  <Resource Include="Assets\Images\alipay_logo.png" />
	  <Resource Include="Assets\Images\auraecho.png" />
	  <Resource Include="Assets\Images\market_banner.png" />
	  <Resource Include="Assets\Images\pay_banner.png" />
	  <Resource Include="Assets\Images\pay_banner_shapes.png" />
	  <Resource Include="Assets\Images\wechat_logo.png" />
	</ItemGroup>
</Project>