<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net10.0-windows</TargetFramework>
		<Nullable>enable</Nullable>
		<UseWPF>true</UseWPF>
		<ImplicitUsings>enable</ImplicitUsings>
		<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
	</PropertyGroup>
	<ItemGroup>
	  <Compile Remove="Enums\**" />
	  <EmbeddedResource Remove="Enums\**" />
	  <None Remove="Enums\**" />
	  <Page Remove="Enums\**" />
	</ItemGroup>
  <ItemGroup>
    <PackageReference Include="Prism.Wpf" Version="8.1.97" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\AuraEcho.Telemetry\AuraEcho.Telemetry.csproj" />
    <ProjectReference Include="..\AuraEcho.Logging\AuraEcho.Logging.csproj" />
    <ProjectReference Include="..\AuraEcho.Toolkit\AuraEcho.Toolkit.csproj" />
    <ProjectReference Include="..\..\Shared\AuraEcho.PluginContracts\AuraEcho.PluginContracts.csproj" />
    <ProjectReference Include="..\AuraEcho.Cloud\AuraEcho.Cloud\AuraEcho.Cloud.csproj" />
    <ProjectReference Include="..\AuraEcho.Domain\AuraEcho.Domain.csproj" />
    <ProjectReference Include="..\AuraEcho.Persistence\AuraEcho.Persistence.csproj" />
  </ItemGroup>
</Project>
