// <auto-generated />
using System;
using AuraEcho.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AuraEcho.Core.Migrations
{
    [DbContext(typeof(AuraEchoDbContext))]
    [Migration("20260324184042_userPlugin")]
    partial class userPlugin
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("AuraEcho.Core.Data.Entities.LocalPlugin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("PluginFolder")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("LocalPlugins");
                });

            modelBuilder.Entity("AuraEcho.Core.Data.Entities.UserPlugin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LocalPluginId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LocalPluginId");

                    b.ToTable("UserPlugins");
                });

            modelBuilder.Entity("AuraEcho.Core.Data.Entities.LocalPlugin", b =>
                {
                    b.OwnsOne("AuraEcho.Core.Models.PluginManifest", "Manifest", b1 =>
                        {
                            b1.Property<Guid>("LocalPluginId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Author")
                                .HasColumnType("TEXT");

                            b1.Property<string>("DefaultViewName")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Description")
                                .HasColumnType("TEXT");

                            b1.Property<string>("EntryAssemblyName")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Icon")
                                .HasColumnType("TEXT");

                            b1.Property<Guid>("Id")
                                .HasColumnType("TEXT");

                            b1.Property<string>("PluginName")
                                .HasColumnType("TEXT");

                            b1.Property<string>("Version")
                                .HasColumnType("TEXT");

                            b1.HasKey("LocalPluginId");

                            b1.ToTable("LocalPlugins");

                            b1.WithOwner()
                                .HasForeignKey("LocalPluginId");
                        });

                    b.Navigation("Manifest")
                        .IsRequired();
                });

            modelBuilder.Entity("AuraEcho.Core.Data.Entities.UserPlugin", b =>
                {
                    b.HasOne("AuraEcho.Core.Data.Entities.LocalPlugin", "LocalPlugin")
                        .WithMany()
                        .HasForeignKey("LocalPluginId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LocalPlugin");
                });
#pragma warning restore 612, 618
        }
    }
}
