// <auto-generated />
using System;
using AuraEcho.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AuraEcho.Core.Migrations.Host
{
    [DbContext(typeof(HostDbContext))]
    [Migration("20260604083117_RefactLocalPluginTable")]
    partial class RefactLocalPluginTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("AuraEcho.Core.Data.Entities.InstalledPlugin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("InstaledAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("InstallPath")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSetup")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PluginId")
                        .HasColumnType("TEXT");

                    b.Property<int>("PluginType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("InstalledPlugin");
                });

            modelBuilder.Entity("AuraEcho.Core.Data.Entities.UserPlugin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LocalPluginId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LocalPluginId");

                    b.ToTable("UserPlugin");
                });

            modelBuilder.Entity("AuraEcho.Core.Data.Entities.UserPlugin", b =>
                {
                    b.HasOne("AuraEcho.Core.Data.Entities.InstalledPlugin", "LocalPlugin")
                        .WithMany()
                        .HasForeignKey("LocalPluginId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LocalPlugin");
                });
#pragma warning restore 612, 618
        }
    }
}
