<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<TargetFrameworks>net472;net10.0-windows10.0.18362.0</TargetFrameworks>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.135" />
    <PackageReference Include="Prism.Wpf" Version="8.1.97" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Enums\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AuraEcho.Design\SRC\AuraEcho.Design\AuraEcho.Design.csproj" />
    <ProjectReference Include="..\AuraEcho.PluginContracts\AuraEcho.PluginContracts.csproj" />
  </ItemGroup>

</Project>
