<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net472;net10.0-windows</TargetFrameworks>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.142" />
    <PackageReference Include="Prism.Wpf" Version="8.1.97" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AuraEcho.Design\SRC\AuraEcho.Design\AuraEcho.Design.csproj" />
    <ProjectReference Include="..\AuraEcho.PluginContracts\AuraEcho.PluginContracts.csproj" />
    <ProjectReference Include="..\AuraEcho.Toolkit\AuraEcho.Toolkit.csproj" Condition="'$(TargetFramework)' == 'net10.0-windows'" />
  </ItemGroup>

</Project>
